name: SAFEEngine
description: SAFEEngine indexer
networks:
  - id: 420 # OP Goerli
    rpc_config:
        url: https://opt-goerli.g.alchemy.com/v2/VL0RGEZAdPee5T2K3NgDN6-37tbwmPV4
        unstable__sync_config:
            initial_block_interval: 1000000
            interval_ceiling: 1000000
    start_block: 0
    contracts:
      - name: SAFEEngine
        abi_file_path: abis/SAFEEngine.json
        address: "0x4ADe84BB4da143af07F9f89E00B65E3a08E2035A"
        handler: src/EventHandlers.ts
        events:
          - event: "ModifySAFECollateralization"
